INSERT INTO events (event_name, imgName, imgAlt, event_date, event_description) VALUES ("2021 President's Scholarship Ball", "sb7.jpg", "A couple examining the menu at the UVU Scholarship Ball", '2021-10-23 18:00:00', "The Utah Valley University (UVU) Scholarship Ball is an opportunity for the community to come together in sponsorship of worthy students pursuing their educational goals. This rich tradition has been carried out for more than 30 years. The 2021 President's Scholarship Ball will be an opportunity to gather as a statewide community to support the educational dreams of aspiring students.");
INSERT INTO events (event_name, imgName, imgAlt, event_date, event_description) VALUES ('2021 Summer Event', "sb7.jpg", "A couple examining the menu at the UVU Scholarship Ball", '2021-06-14 18:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget tortor diam. Curabitur ac elit in dui semper iaculis quis a lorem. Duis at placerat elit. Nulla nec felis placerat quam tristique convallis eget nec nibh. Morbi vel rhoncus augue, sit amet pharetra neque. Fusce odio neque, semper in sodales vel, fringilla sed quam. Cras pretium mauris mi, at efficitur sem elementum eget. Fusce fermentum massa odio. Aliquam venenatis magna libero, quis pulvinar ex tincidunt sagittis.');
INSERT INTO events (event_name, imgName, imgAlt, event_date, event_description) VALUES ('2021 Winter Event', "sb7.jpg", "A couple examining the menu at the UVU Scholarship Ball", '2022-01-28 18:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget tortor diam. Curabitur ac elit in dui semper iaculis quis a lorem. Duis at placerat elit. Nulla nec felis placerat quam tristique convallis eget nec nibh. Morbi vel rhoncus augue, sit amet pharetra neque. Fusce odio neque, semper in sodales vel, fringilla sed quam. Cras pretium mauris mi, at efficitur sem elementum eget. Fusce fermentum massa odio. Aliquam venenatis magna libero, quis pulvinar ex tincidunt sagittis.');

INSERT INTO upNext (title, imgName, imgAlt, summary, link) VALUES ('UVU Launches Wolverines Elevated', "mnca.jpg", "UVU Launches Wolverines Elevated", 'A new program at Utah Valley University aims to help students with intellectual disabilities lead fulfilled and independent lives.', 'https://www.uvu.edu/advancement/upnext/2021/uvuwolverineselevated.html');
INSERT INTO upNext (title, imgName, imgAlt, summary, link) VALUES ('UVU Students LIFT Each Other Up Through 2518 Campaign', "2518logoweb.jpg", "UVU Students LIFT Each Other Up Through 2518 Campaign", 'In April 2021, the Utah Valley University Student Alumni Association (UVUSAA) hosted another successful year of the 2518 campaign.', 'https://www.uvu.edu/advancement/upnext/2021/2518-campaign.html');
INSERT INTO upNext (title, imgName, imgAlt, summary, link) VALUES ('Aviation Graduate Soars', "aviation21.jpg", "Aviation Graduate Soars", "UVU graduate Katie Lin ('21) takes to new heights as she fulfills her dream to become a pilot despite cultural opposition.", 'https://www.uvu.edu/advancement/upnext/2021/aviationgrad.html');
INSERT INTO upNext (title, imgName, imgAlt, summary, link) VALUES ('Donor and Associate Dean: Why Keith Mulbery Gives', "cet-building.jpg", "Donor and Associate Dean: Why Keith Mulbery Gives", 'Keith Mulbery is an associate dean in the College of Engineering and Technology at UVU. He shares why he donates to UVU.', 'https://www.uvu.edu/advancement/upnext/2021/donor-dean-gives.html');
INSERT INTO upNext (title, imgName, imgAlt, summary, link) VALUES ("Crystal's Path to Changing Lives", "crystal-teaching.jpg", "Crystal's Path to Changing Lives", "Growing up, Crystal Sedano didn't know if she'd make it to college. Now, she aspires to help her students the way donors and her teachers helped her.", 'https://www.uvu.edu/advancement/upnext/2021/crystalsedano.html');
INSERT INTO upNext (title, imgName, imgAlt, summary, link) VALUES ('Endowing Excellence', "header3.jpg", "Endowing Excellence", 'Learn how contributing to an endowment fund can help create your legacy.', 'https://www.uvu.edu/advancement/upnext/2021/endowing-excellence.html');